config/routes.rb
Rails.application.routes.draw do
   get '/signup', to: 'users#new' 
  get '/signin', to: 'sessions#new'
  get '/signout', to: 'sessions#destroy'

  resource :sessions, only: [:create]
  resources :users, only: [:create]
  resources :guides
  
  root 'home#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/guide.rb
class Guide < ApplicationRecord
    has_one_attached :image
    belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
    validates :email, uniqueness: true
    validates :email, presence: true
    validates :password, length: { minimum: 5, allow_nil: true }
    has_many :guides
  
    def password
      @password
    end
  
    def password=(raw)
      @password = raw
      self.password_digest = BCrypt::Password.create(raw)
    end
  
    def is_password?(raw)
      BCrypt::Password.new(password_digest).is_password?(raw)
    end
  end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def ensure_current_user
    if current_user.nil?
      redirect_to "/"
    end
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end
  end
end

app/controllers/guides_controller.rb
class GuidesController < ApplicationController
  before_action :set_guide, only: %i[ show edit update destroy ]
  before_action :ensure_current_user

  # GET /guides or /guides.json
  def index
    @guides = current_user.guides
  end

  # GET /guides/1 or /guides/1.json
  def show
  end

  # GET /guides/new
  def new
    @guide = Guide.new
  end

  # GET /guides/1/edit
  def edit
  end

  # POST /guides or /guides.json
  def create
    @guide = current_user.guides.new(guide_params)
    

    respond_to do |format|
      if @guide.save
        format.html { redirect_to guide_url(@guide), notice: "Guide was successfully created." }
        format.json { render :show, status: :created, location: @guide }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @guide.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guides/1 or /guides/1.json
  def update
    respond_to do |format|
      if @guide.update(guide_params)
        format.html { redirect_to guide_url(@guide), notice: "Guide was successfully updated." }
        format.json { render :show, status: :ok, location: @guide }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @guide.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guides/1 or /guides/1.json
  def destroy
    @guide.destroy

    respond_to do |format|
      format.html { redirect_to guides_url, notice: "Guide was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guide
      @guide = current_user.guides.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def guide_params
      params.require(:guide).permit(:name, :location, :rate, :image)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    # lookup the user in the database
    @user = User.find_by(email: user_params[:email])

    if @user && @user.is_password?(user_params[:password])
      session[:user_id] = @user.id
      redirect_to guides_path
    else
      flash.now[:notice] = "Invalid email or password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to guides_path
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to guides_path
    else
      flash.now[:notice] = @user.errors.full_messages.to_sentence
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guides_helper.rb
module GuidesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/guides/_form.html.erb
<%= form_with(model: guide, class:"w-25") do |form| %>
  <% if guide.errors.any? %>
    <div >
      <h2><%= pluralize(guide.errors.count, "error") %> prohibited this guide from being saved:</h2>

      <ul>
        <% guide.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :image %>
    <%= form.file_field :image, class:"form-control"  %>
  </div>

  

  <div class="form-group">
    <%= form.label :location %>
    <%= form.text_field :location, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :rate %>
    <%= form.number_field :rate, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>

</body>

app/views/guides/_guide.html.erb
<body class=guides-show>

<div class="container" id="<%= dom_id guide %>">
<section class="guide-list">
  <p>
    <strong>Name:</strong>
    <%= guide.name %>
  </p>

  <p>
  <strong >Image:</strong>
  <%= image_tag(guide.image, style:"width:300px; height:300px", class: "image") if guide.image.attached?%>

</p>

  <p>
    <strong>Location:</strong>
    <%= guide.location %>
  </p>

  <p>
    <strong>Rate:</strong>
    <%= guide.rate %>
  </p>
  </section>

</div>
</body>

app/views/guides/edit.html.erb
  <body class="edit-form">
 
 <nav class="navbar navbar-expand-lg navbar-dark ">
  <div class="container-fluid">
    
    <%= link_to "Tourist Connect", root_path, class:"navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
        <%= link_to "Home", root_path, class:"nav-link active"%>
       
        </li>
       
        <li class="nav-item">
          <%= link_to "Reviews", guides_path, class:"nav-link"%>
        </li>
    
        <li class="nav-item">
          <%= link_to "Add Review", new_guide_path, class:"nav-link"%>
        </li>

      </ul>
      <ul class="navbar-nav">
      <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        Get Started!
      </a>
      <ul class="dropdown-menu dropdown-menu-end ">
        <li><a class="dropdown-item" href="/signup">Sign Up</a></li>
        <li><a class="dropdown-item" href="/signin">Sign In</a></li>
        
        <li><a class="dropdown-item" href="/signout">Sign Out</a></li>
      </ul>
    </li>
    </ul>
    </div> 
  </div>
</nav>



<div class="review">
<h1 class="edit-name">Editing guide</h1>

<%= render "form", guide: @guide %>

<br>

<div>
  <%= link_to "Show this guide", @guide, class: "link2" %> |
  <%= link_to "Back to guides", guides_path, class: "link2" %>
</div>

</div>
</div>

</body>

app/views/guides/index.html.erb
<nav class="navbar navbar-expand-lg  ">

  <div class="container-fluid">
    
    <%= link_to "Tourist Connect", root_path, class:"navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
        <%= link_to "Home", root_path, class:"nav-link active"%>
       
        </li>
       
        <li class="nav-item">
          <%= link_to "Reviews", guides_path, class:"nav-link"%>
        </li>
    
        <li class="nav-item">
          <%= link_to "Add Review", new_guide_path, class:"nav-link"%>
        </li>

      </ul>
      <ul class="navbar-nav">
      <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        Get Started!
      </a>
      <ul class="dropdown-menu dropdown-menu-end ">
        <li><a class="dropdown-item" href="/signup">Sign Up</a></li>
        <li><a class="dropdown-item" href="/signin">Sign In</a></li>
        
        <li><a class="dropdown-item" href="/signout">Sign Out</a></li>
      </ul>
    </li>
    </ul>
    </div> 
  </div>
</nav>
<p class="display-index"><%= notice %></p>

<h1 class="container">Reviews</h1>

<div  id="guides">
  <% @guides.each do |guide| %>
    <%= render guide %>
  
    <p class="guide">
        <%= link_to "Show this guide", guide, class:"btn btn-outline-info" %>
    </p>
  <% end %>
</div>

app/views/guides/new.html.erb
 <body class="form">
 <nav class="navbar navbar-expand-lg navbar-dark ">
  <div class="container-fluid">
    
    <%= link_to "Tourist Connect", root_path, class:"navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
        <%= link_to "Home", root_path, class:"nav-link active"%>
       
        </li>
       
        <li class="nav-item">
          <%= link_to "Reviews", guides_path, class:"nav-link"%>
        </li>
    
        <li class="nav-item">
          <%= link_to "Add Review", new_guide_path, class:"nav-link"%>
        </li>

      </ul>
      <ul class="navbar-nav">
      <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        Get Started!
      </a>
      <ul class="dropdown-menu dropdown-menu-end ">
        <li><a class="dropdown-item" href="/signup">Sign Up</a></li>
        <li><a class="dropdown-item" href="/signin">Sign In</a></li>
        
        <li><a class="dropdown-item" href="/signout">Sign Out</a></li>
      </ul>
    </li>
    </ul>
    </div> 
  </div>
</nav>

<div class="review">
<div>
<h1>New review</h1>

<%= render "form", guide: @guide %>

<br>

<div>
  <%= link_to "Back ", guides_path, class: "link2" %>
</div>

</div>
</div>
</body>

app/views/guides/show.html.erb
<nav class="navbar navbar-expand-lg  ">
  <div class="container-fluid">
    
    <%= link_to "Tourist Connect", root_path, class:"navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
        <%= link_to "Home", root_path, class:"nav-link active"%>
       
        </li>
       
        <li class="nav-item">
          <%= link_to "Reviews", guides_path, class:"nav-link"%>
        </li>
    
        <li class="nav-item">
          <%= link_to "Add Review", new_guide_path, class:"nav-link"%>
        </li>

      </ul>
      <ul class="navbar-nav">
      <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        Get Started!
      </a>
      <ul class="dropdown-menu dropdown-menu-end ">
        <li><a class="dropdown-item" href="/signup">Sign Up</a></li>
        <li><a class="dropdown-item" href="/signin">Sign In</a></li>
        
        <li><a class="dropdown-item" href="/signout">Sign Out</a></li>
      </ul>
    </li>
    </ul>
    </div> 
  </div>
</nav>
<p class=display-show><%= notice %></p>
<%= render @guide %>

<div class="button">
  <%= link_to "Edit ", edit_guide_path(@guide), class:"btn btn-outline-info" %>
  <%= link_to "Back ", guides_path, class:"btn btn-outline-info" %>

  <%= button_to "Delete", @guide, method: :delete, class:"btn btn-outline-info" %>
</div>

app/views/home/index.html.erb
<%= stylesheet_link_tag "application.css" %>
<body
>
<nav class="navbar navbar-expand-lg navbar-dark ">
  <div class="container-fluid">
    
    <%= link_to "Tourist Connect", root_path, class:"navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
        <%= link_to "Home", root_path, class:"nav-link active"%>
       
        </li>
       
        <li class="nav-item">
          <%= link_to "Reviews", guides_path, class:"nav-link"%>
        </li>
    
        <li class="nav-item">
          <%= link_to "Add Review", new_guide_path, class:"nav-link"%>
        </li>

      </ul>
      <ul class="navbar-nav">
      <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        Get Started!
      </a>
      <ul class="dropdown-menu dropdown-menu-end ">
        <li><a class="dropdown-item" href="/signup">Sign Up</a></li>
        <li><a class="dropdown-item" href="/signin">Sign In</a></li>
        
        <li><a class="dropdown-item" href="/signout">Sign Out</a></li>
      </ul>
    </li>
    </ul>
    </div> 
  </div>
</nav>

<body class="home-body">
<img class="bg-img"src="https://images.unsplash.com/photo-1634942062514-6e00d236759d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1770&q=80 ">
<h1 class="centered">Welcome to Tourist Connect</h1>
<a class="centered2" href="/signup">Get Started</a>
</body>

</body>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark ">
  <div class="container-fluid">
    
    <%= link_to "Tourist Connect", root_path, class:"navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
        <%= link_to "Home", root_path, class:"nav-link active"%>
       
        </li>
       
        <li class="nav-item">
          <%= link_to "Reviews", guides_path, class:"nav-link"%>
        </li>
    
        <li class="nav-item">
          <%= link_to "Add Review", new_guide_path, class:"nav-link"%>
        </li>

      </ul>
      <ul class="navbar-nav">
      <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        Get Started!
      </a>
      <ul class="dropdown-menu dropdown-menu-end ">
        <li><a class="dropdown-item" href="/signup">Sign Up</a></li>
        <li><a class="dropdown-item" href="/signin">Sign In</a></li>
        
        <li><a class="dropdown-item" href="/signout">Sign Out</a></li>
      </ul>
    </li>
    </ul>
    </div> 
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tourist Connect</title>
    <%= stylesheet_link_tag "application.css" %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
   
    
 
    <div >

      <% if current_user %>
     
    <% end %>
<%= yield %>
    </div>
    
  </body>
</html>

app/views/users/new.html.erb
<p id="notice"><%= notice %></p>
<body class="scroll">

<nav class="navbar navbar-expand-lg ">
  <div class="container-fluid">
    
    <%= link_to "Tourist Connect", root_path, class:"navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
        <%= link_to "Home", root_path, class:"nav-link active"%>
       
        </li>
       
        <li class="nav-item">
          <%= link_to "Reviews", guides_path, class:"nav-link"%>
        </li>
    
        <li class="nav-item">
          <%= link_to "Add Review", new_guide_path, class:"nav-link"%>
        </li>

      </ul>
      <ul class="navbar-nav">
      <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        Get Started!
      </a>
      <ul class="dropdown-menu dropdown-menu-end ">
        <li><a class="dropdown-item" href="/signup">Sign Up</a></li>
        <li><a class="dropdown-item" href="/signin">Sign In</a></li>
        
        <li><a class="dropdown-item" href="/signout">Sign Out</a></li>
      </ul>
    </li>
    </ul>
    </div> 
  </div>
</nav>


<section class="vh-100">
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-6 text-black">

        <div class="px-3 ms-xl-3">
      
          <span class="h1 fw-bold mb-2">Tourist Connect</span>
        </div>

        <div class="d-flex align-items-center h-custom-3 px-5 ms-xl-4 mt-5 pt-5 pt-xl-0 mt-xl-n5">

        
  <form action="/users" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" style="width: 23rem;">

            <h3 class="fw-normal mb-4 pb-3" style="letter-spacing: 1px;">Sign up</h3>

            <div class="form-outline mb-4">
              <input type="email" id="form2Example18" class="form-control form-control-lg" name="user[email]" value="<%= @user.email %>"/>
              <label class="form-label" for="form2Example18">Email address</label>
            </div>

            <div class="form-outline mb-4">
              <input type="password" id="form2Example28" class="form-control form-control-lg" name="user[password]" />
              <label class="form-label" for="form2Example28">Password</label>
            </div>

            <div class="pt-1 mb-4">
              <input type="submit" value="Sign up" class="btn btn-info btn-lg btn-block">
            </div>

            
            

          </form>

        </div>

      </div>
      <div class="col-sm-6 px-0 d-none d-sm-block">
        <img class="img3"src="https://images.unsplash.com/photo-1669111958180-c734079d56bf?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80"
          alt="Login image" class="w-100 vh-100" style="object-fit: cover; object-position: left;">
      </div>
    </div>
  </div>
</section>

</body>